version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: inquisitive-backend-dev
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - REDIS_URL=redis://redis-stack:6379
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app/backend
      - /app/backend/node_modules
      - ./tsconfig.base.json:/app/tsconfig.base.json
    depends_on:
      - redis-stack

  redis-stack:
    image: redis/redis-stack:latest
    container_name: inquisitive-redis-stack
    ports:
      - "6379:6379"
      - "8001:8001" # RedisInsight GUI port
    volumes:
      - redis-data:/data

volumes:
  redis-data:
